import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const redHat = Red_Hat_Display({
  variable: "--font-redHat",
  subsets:['latin']
});

export const metadata: Metadata = {
  title: "PhishAware",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={` ${redHat.variable}  antialiased min-w-4xl`}>
        <div className="flex h-screen max-h-screen overflow-hidden">
          <Sidebar />
          <main className="flex-1 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
